export const PLATFORM = {
  COURSE_AREA: "PLATFORM_COURSE_AREA",
  COURSE_SUB_AREA: "PLATFORM_COURSE_SUB_AREA",
  SET_COURSE_DETAILS: "PLATFORM_COURSE_DETAILS",
  MATERIAL_CATEGORY: "PLATFORM_MATERIAL_CATEGORY",
  MULTIPLE_VALUES: "PLATFORM_MULTIPLE_VALUES",
};

export const CONTENT = {
  GET_ALL: "GET_ALL_CONTENT",
};

export const MULTIPLE_VALUES = "SET_MULTIPLE_VALUES";
export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const MESSAGE = {
  DISPLAY: "DISPLAY_MESSAGE",
  NORMAL: "NORMAL",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  CLEAN_ERROR: "CLEAN_ERROR",
  WRONG_DATA: "WRONG_DATA",
  NETWORK_ERROR: "NETWORK_ERROR",
  WRONG_LOGIN_CREDENTIALS: "WRONG_LOGIN_CREDENTIALS",
  ACCESS_DENIED: "ACCESS_DENIED",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
};
export const LOADER = {
  CONTENT: "CONTENT_LOADER",
  HOME_CONTENT: "HOME_CONTENT_LOADER",
};

export const GET_CONTENT = "GET_CONTENT";
